// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqNkhh1jytmVQSV9CZRq08oWcgPMM3Uz4',
    appId: '1:592600081254:web:e5e1a99922b7761ec11ea7',
    messagingSenderId: '592600081254',
    projectId: 'da-nen-tang-a7f74',
    authDomain: 'da-nen-tang-a7f74.firebaseapp.com',
    storageBucket: 'da-nen-tang-a7f74.appspot.com',
    measurementId: 'G-9VRC1CZ0ZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpys7gavrR-9IEw2FCPiN1yQ3h3le6bCo',
    appId: '1:592600081254:android:2ac82dde15ba9ad8c11ea7',
    messagingSenderId: '592600081254',
    projectId: 'da-nen-tang-a7f74',
    storageBucket: 'da-nen-tang-a7f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtCX_o9BGLXeXj6vAKdIvIZVHenoL3y1s',
    appId: '1:592600081254:ios:02ededb8c2352683c11ea7',
    messagingSenderId: '592600081254',
    projectId: 'da-nen-tang-a7f74',
    storageBucket: 'da-nen-tang-a7f74.appspot.com',
    iosBundleId: 'com.example.appGk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtCX_o9BGLXeXj6vAKdIvIZVHenoL3y1s',
    appId: '1:592600081254:ios:02ededb8c2352683c11ea7',
    messagingSenderId: '592600081254',
    projectId: 'da-nen-tang-a7f74',
    storageBucket: 'da-nen-tang-a7f74.appspot.com',
    iosBundleId: 'com.example.appGk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqNkhh1jytmVQSV9CZRq08oWcgPMM3Uz4',
    appId: '1:592600081254:web:dcedb1021dd4ac54c11ea7',
    messagingSenderId: '592600081254',
    projectId: 'da-nen-tang-a7f74',
    authDomain: 'da-nen-tang-a7f74.firebaseapp.com',
    storageBucket: 'da-nen-tang-a7f74.appspot.com',
    measurementId: 'G-TM15H2Z82K',
  );

}